In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r'C:\Users\mdgha\Downloads\CarPrice_Assignment.csv')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [3]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [7]:
df.shape

(205, 26)

In [4]:
df.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [16]:
df['CarName'].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 4', 'mazda glc custom l', 'mazda glc custom',
       'buick electra 225 custom', 'buick century luxus (sw)',
       'buick century', 'buick skyhawk', 'buick opel isuzu deluxe',
       'buick skylark', 'buick century special',
       'buick regal sport coupe (turbo)', 'mercury cougar',
       'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander',
       'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero',
       'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue',
       'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke',
       'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz',
       'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks',
       'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl',
       'peugeot 505s turbo diesel', 'plymouth fury iii',
       'plymouth cricket', 'plymouth satellite custom (sw)',
       'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster',
       'porsche macan', 'porcshce panamera', 'porsche cayenne',
       'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e',
       'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz',
       'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia',
       'subaru tribeca', 'toyota corona mark ii', 'toyota corona',
       'toyota corolla 1200', 'toyota corona hardtop',
       'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii',
       'toyota corolla', 'toyota corolla liftback',
       'toyota celica gt liftback', 'toyota corolla tercel',
       'toyota corona liftback', 'toyota starlet', 'toyota tercel',
       'toyota cressida', 'toyota celica gt', 'toyouta tercel',
       'vokswagen rabbit', 'volkswagen 1131 deluxe sedan',
       'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)',
       'volkswagen super beetle', 'volkswagen dasher', 'vw dasher',
       'vw rabbit', 'volkswagen rabbit', 'volkswagen rabbit custom',
       'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245',
       'volvo 264gl', 'volvo diesel', 'volvo 246'], dtype=object)

In [48]:
def brand(row):
    new = []
    for i in range(len(row)):
        val = (row[i].split())[0]
        if val == 'porcshce':
            val = 'porsche'
        new.append(val.lower())

    return new

df['CarName'] = brand(df['CarName'])

In [49]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [50]:
df['CarName'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'buick', 'mercury', 'mitsubishi',
       'nissan', 'peugeot', 'plymouth', 'porsche', 'renault', 'saab',
       'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [63]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [77]:
df.drop(columns='car_ID', inplace=True)

In [74]:
from sklearn.preprocessing import LabelEncoder

In [78]:
label = LabelEncoder()
df1 = df.copy()

In [79]:
df1

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi,gas,std,4,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi,gas,std,4,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,gas,std,4,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,volvo,gas,turbo,4,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,volvo,gas,std,4,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,volvo,diesel,turbo,4,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,volvo,gas,turbo,4,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [101]:
att = ['drivewheel', 'fuelsystem']
for a in att:
    df1[a] = label.fit_transform(df1[a])

In [452]:
X1 = df1.drop(columns='price')
y1 = df1.price

In [434]:
from sklearn.preprocessing import StandardScaler

#Scaling the features, so it provides a better output
scaler = StandardScaler()
df2 = scaler.fit_transform(df1)

df2 = pd.DataFrame(df2)

In [435]:
X = df2.iloc[:, :-1]
y = df2.iloc[:, -1]

In [437]:
X

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1.743470,-1.945332,0.328798,-0.469295,-1.130388,-3.050975,1.213330,-0.121867,-1.690772,-0.426521,...,-0.378892,0.074449,0.869568,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059
1,1.743470,-1.945332,0.328798,-0.469295,-1.130388,-3.050975,1.213330,-0.121867,-1.690772,-0.426521,...,-0.378892,0.074449,0.869568,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059
2,0.133509,-1.945332,0.328798,-0.469295,-1.130388,-0.717207,1.213330,-0.121867,-0.708596,-0.231513,...,1.872496,0.604046,0.869568,-2.404880,0.685946,-0.288349,1.264536,-0.262960,-0.953012,-0.691627
3,0.938490,-1.785879,0.328798,-0.469295,0.884652,0.449677,-0.589081,-0.121867,0.173698,0.207256,...,-0.378892,-0.431076,0.869568,-0.517266,0.462183,-0.035973,-0.053668,0.787855,-0.186865,-0.109354
4,0.938490,-1.785879,0.328798,-0.469295,0.884652,0.449677,-2.391492,-0.121867,0.107110,0.207256,...,0.746802,0.218885,0.869568,-0.517266,0.462183,-0.540725,0.275883,0.787855,-1.106241,-1.273900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1.476452,1.403191,0.328798,-0.469295,0.884652,0.449677,1.213330,-0.121867,1.721873,1.198549,...,-0.378892,0.339248,0.869568,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.340094,-0.400490
201,-1.476452,1.403191,0.328798,2.130854,0.884652,0.449677,1.213330,-0.121867,1.721873,1.198549,...,-0.378892,0.339248,0.869568,1.666445,-0.336970,-0.364062,1.416637,0.367529,-0.953012,-0.837195
202,-1.476452,1.403191,0.328798,-0.469295,0.884652,0.449677,1.213330,-0.121867,1.721873,1.198549,...,1.872496,1.109571,0.869568,0.926204,-1.232021,-0.338824,0.757535,0.787855,-1.106241,-1.128332
203,-1.476452,1.403191,-3.041381,2.130854,0.884652,0.449677,1.213330,-0.121867,1.721873,1.198549,...,1.872496,0.435538,-0.126306,-1.183483,0.462183,3.244916,0.047732,-0.683286,0.119594,-0.546059
204,-1.476452,1.403191,0.328798,2.130854,0.884652,0.449677,1.213330,-0.121867,1.721873,1.198549,...,-0.378892,0.339248,0.869568,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.953012,-0.837195

In [436]:
y

0      0.027391
1      0.404461
2      0.404461
3      0.084485
4      0.523668
         ...
200    0.447752
201    0.723810
202    1.029983
203    1.153582
204    1.173031
Name: 24, Length: 205, dtype: float64

**Linear Regression using Gradient Descent**

In [445]:
#Uses the linear equation of the regression line to predict the output
def predict(X, theta, b):
    return X.dot(theta) + b

#Loss function
def mean_sum_of_squares_error(X, y, theta, b):
    m = len(y)
    prediction = predict(X, theta, b)
    loss = (1/(2*m))*np.sum((y - prediction)**2)
    return loss


#Applying Gradient Descent to update the weights and bias
def gradient_descent(X, y, theta, b):
    m = len(y)

    grad_theta = np.zeros(len(theta))
    gradient_b = 0

    pred = predict(X, theta, b)

    gradient_b = -(1/m) * np.sum(y - pred)
    for j in range(len(theta)):
        grad_theta[j] = -(1/m) * np.sum((y - pred)*X.iloc[:, j])
        
    b = b - 0.01*gradient_b
    for j in range(len(theta)):
        theta[j] = theta[j] - 0.01*grad_theta[j]

    return theta, b

def linear_regression(X, y):
    theta = np.zeros(X.shape[1])
    b = 0
    loss_val = []
    for i in range(5000):
        theta, b = gradient_descent(X, y, theta, b)
        if i%100==0:
            loss = mean_sum_of_squares_error(X, y, theta, b)
            loss_val.append(f"Cost at iteration {i}: {loss}")
        
    return theta, loss_val, b

In [446]:
theta, loss_history, b = linear_regression(X, y)
print("Optimized theta:", theta) #Prints the weights for each feature
print("Optimized bias (b):", b)  
for loss in loss_history:
    print(loss)

Optimized theta: [ 0.01458432 -0.17594776 -0.00155228  0.01064399  0.04517586 -0.09300695
  0.05941179  0.16892955  0.096204   -0.00186428  0.13637039  0.07119454
  0.17825161  0.02927122 -0.00995829  0.39630367  0.01383737 -0.03071935
 -0.10558781  0.05735603  0.18848275  0.07345382 -0.01188169  0.06086904]
Optimized bias (b): 3.927914903903094e-16
Cost at iteration 0: 0.4407984147386586
Cost at iteration 100: 0.06135364800585622
Cost at iteration 200: 0.05558761662682946
Cost at iteration 300: 0.05407763108868382
Cost at iteration 400: 0.053312795628556855
Cost at iteration 500: 0.05280681925422865
Cost at iteration 600: 0.05243504381355153
Cost at iteration 700: 0.05214638554581574
Cost at iteration 800: 0.05191390891779627
Cost at iteration 900: 0.05172154547041368
Cost at iteration 1000: 0.05155904200650338
Cost at iteration 1100: 0.05141955193222142
Cost at iteration 1200: 0.05129832908437108
Cost at iteration 1300: 0.051191968392961903
Cost at iteration 1400: 0.05109794648911507
Cost at iteration 1500: 0.05101433621920441
Cost at iteration 1600: 0.05093962528077457
Cost at iteration 1700: 0.050872598545865726
Cost at iteration 1800: 0.05081226000860383
Cost at iteration 1900: 0.050757779779548894
Cost at iteration 2000: 0.05070845717222773
Cost at iteration 2100: 0.05066369431210901
Cost at iteration 2200: 0.05062297676029266
Cost at iteration 2300: 0.05058585891360545
Cost at iteration 2400: 0.05055195273222299
Cost at iteration 2500: 0.05052091884197201
Cost at iteration 2600: 0.05049245937358245
Cost at iteration 2700: 0.0504663121037365
Cost at iteration 2800: 0.05044224559470843
Cost at iteration 2900: 0.05042005511658668
Cost at iteration 3000: 0.05039955919462594
Cost at iteration 3100: 0.050380596664304514
Cost at iteration 3200: 0.050363024144551606
Cost at iteration 3300: 0.050346713859444864
Cost at iteration 3400: 0.05033155175308946
Cost at iteration 3500: 0.0503174358530872
Cost at iteration 3600: 0.0503042748461138
Cost at iteration 3700: 0.05029198683539555
Cost at iteration 3800: 0.0502804982548195
Cost at iteration 3900: 0.05026974291837016
Cost at iteration 4000: 0.05025966118680493
Cost at iteration 4100: 0.05025019923612815
Cost at iteration 4200: 0.050241308414627
Cost at iteration 4300: 0.05023294467707921
Cost at iteration 4400: 0.050225068086304524
Cost at iteration 4500: 0.05021764237355773
Cost at iteration 4600: 0.05021063455039356
Cost at iteration 4700: 0.05020401456560576
Cost at iteration 4800: 0.050197755001675975
Cost at iteration 4900: 0.050191830805889445

In [440]:
predict(X, theta, b)

0      0.334080
1      0.334080
2      0.826379
3      0.094601
4      0.380560
         ...
200    0.511954
201    0.740020
202    1.053958
203    0.691178
204    0.558081
Length: 205, dtype: float64

**Least Square Method**

In [443]:
def predict(X, theta, b):
    return X.dot(theta) + b

def mean_sum_of_squares_error(X, y, theta, b):
    m = len(y)
    prediction = predict(X, theta, b)
    loss = (1/(2*m))*np.sum((y - prediction)**2)
    return loss

def get_mean(X):
    n = X.shape[1]
    mean_vals = np.zeros(n)
    for i in range(n):
        mean_vals[i] = np.mean(X.iloc[:, i])
    return mean_vals

def update_bias(X, y, theta):
    x_mean = get_mean(X)
    y_mean = np.mean(y)
    total_weight = x_mean.dot(theta)
    bias = (y_mean - total_weight)
    return bias

def update_theta(X, y, theta):
    n = X.shape[1]
    x_mean = get_mean(X)
    y_mean = np.mean(y)
    weights = np.zeros(n)
    
    for i in range(n):
        numerator1 = 0
        numerator2 = 0
        denominator = 0

        for j in range(n):
            if i == j:
                numerator1 += np.sum((X.iloc[:, j] - mean_val[j]) * (y - mean_val[i]))
                denominator += np.sum((X.iloc[:, j] - mean_val[j]) ** 2)
            else:
                numerator2 += theta[j] * np.sum((X.iloc[:, j] - mean_val[j]) * (X.iloc[:, i] - mean_val[i]))

        theta[i] = ((numerator1 - numerator2) / denominator)

    return theta


def least_square_method(X, y):
    b = 0
    theta = np.zeros(X.shape[1])
    loss_val = []
    for i in range(1000):
        if i%100==0:
            loss_val.append(f"At iteration {i} - Loss: {mean_sum_of_squares_error(X, y, theta, b)}")
        b = update_bias(X, y, theta)
        theta = update_theta(X, y, theta)

    return theta, b, loss_val

In [453]:
theta_least_square, b_least_square, loss_val = least_square_method(X1, y1)

In [454]:
theta_least_square

array([ 5.19562037e+01, -2.24837343e+02,  2.56303293e+03,  5.45742307e+02,
        3.45436422e+02, -8.14175192e+02,  8.44428534e+02,  1.12586804e+04,
        1.21474082e+02, -1.42011804e+01,  5.43003638e+02,  2.51369177e+02,
        2.57008502e+00,  1.76041224e+02, -3.28428925e+02,  8.76310262e+01,
        7.31105824e+01, -1.22330322e+03, -2.82966476e+03,  3.05593682e+02,
        3.24750574e+01,  1.23467566e+00, -8.77174031e+01,  1.18071365e+02])

In [455]:
b_least_square

-64119.941873916425

In [456]:
loss_val

['At iteration 0 - Loss: 119890739.74557047',
 'At iteration 100 - Loss: 3181727.8619252974',
 'At iteration 200 - Loss: 3178181.1788705983',
 'At iteration 300 - Loss: 3177731.489672652',
 'At iteration 400 - Loss: 3177675.3534424016',
 'At iteration 500 - Loss: 3177668.3354812297',
 'At iteration 600 - Loss: 3177667.45801473',
 'At iteration 700 - Loss: 3177667.3483027997',
 'At iteration 800 - Loss: 3177667.3345852224',
 'At iteration 900 - Loss: 3177667.3328700773']